package com.fyp.healthcare

/**
 * A built-in list of commonly prescribed medications with a plain-language note on
 * what each one is for. Used by the "Choose Medication" picker on the Add Medication
 * screen so the user doesn't have to type (or spell) a drug name.
 *
 * This is a curated set of the medicines people most often take on a schedule — it is
 * NOT the entire drugs.com A–Z database (that is licensed data and tens of thousands of
 * entries). Anything not listed is covered by the picker's "Add a medication not listed"
 * option, where the user types their own name and an optional description.
 *
 * Descriptions are short, general information written for this app — not dosing advice.
 */
object MedicationCatalog {

    data class Entry(
        val name: String,
        val description: String,
        val route: MedRoute = MedRoute.ORAL,
    ) {
        /** "A".."Z" for a normal name, "#" for anything starting with a digit/symbol. */
        val section: String get() = name.firstOrNull()?.uppercaseChar()?.let {
            if (it in 'A'..'Z') it.toString() else "#"
        } ?: "#"

        fun matches(query: String): Boolean {
            val q = query.trim().lowercase()
            return q.isEmpty() ||
                name.lowercase().contains(q) ||
                description.lowercase().contains(q)
        }
    }

    /** Every entry, sorted A→Z by name. */
    val ALL: List<Entry> = listOf(
        Entry("Acetaminophen (Tylenol)", "Pain reliever and fever reducer"),
        Entry("Acetazolamide", "Carbonic anhydrase inhibitor for glaucoma, altitude sickness and seizures"),
        Entry("Acyclovir", "Antiviral for cold sores, genital herpes and shingles"),
        Entry("Albuterol (salbutamol)", "Inhaled reliever that opens the airways in asthma and COPD", MedRoute.INHALED),
        Entry("Alendronate", "Bisphosphonate that strengthens bone in osteoporosis"),
        Entry("Allopurinol", "Lowers uric acid to prevent gout attacks"),
        Entry("Alprazolam (Xanax)", "Benzodiazepine for anxiety and panic disorder"),
        Entry("Amiodarone", "Antiarrhythmic that steadies irregular heart rhythms"),
        Entry("Amitriptyline", "Tricyclic antidepressant, also used for nerve pain and migraine prevention"),
        Entry("Amlodipine", "Calcium channel blocker for high blood pressure and angina"),
        Entry("Amoxicillin", "Penicillin antibiotic for common bacterial infections"),
        Entry("Amoxicillin/clavulanate (Augmentin)", "Broad-spectrum penicillin antibiotic"),
        Entry("Amphetamine/dextroamphetamine (Adderall)", "Stimulant for ADHD and narcolepsy"),
        Entry("Anastrozole", "Aromatase inhibitor used in breast cancer treatment"),
        Entry("Apixaban (Eliquis)", "Blood thinner that prevents clots and stroke"),
        Entry("Aripiprazole (Abilify)", "Antipsychotic for schizophrenia, bipolar disorder and depression add-on"),
        Entry("Aspirin", "Pain reliever and blood thinner; low dose protects the heart"),
        Entry("Atenolol", "Beta blocker for high blood pressure and angina"),
        Entry("Atomoxetine (Strattera)", "Non-stimulant medicine for ADHD"),
        Entry("Atorvastatin (Lipitor)", "Statin that lowers cholesterol"),
        Entry("Azathioprine", "Immunosuppressant for autoimmune disease and transplants"),
        Entry("Azithromycin (Z-Pak)", "Macrolide antibiotic for respiratory and other infections"),
        Entry("Baclofen", "Muscle relaxant for spasticity"),
        Entry("Beclomethasone", "Inhaled or nasal corticosteroid for asthma and allergies", MedRoute.INHALED),
        Entry("Benazepril", "ACE inhibitor for high blood pressure"),
        Entry("Benzonatate", "Non-narcotic cough suppressant"),
        Entry("Betamethasone", "Topical corticosteroid for skin inflammation", MedRoute.TOPICAL),
        Entry("Bisoprolol", "Beta blocker for high blood pressure and heart failure"),
        Entry("Brimonidine", "Eye drops that lower pressure in glaucoma", MedRoute.OPHTHALMIC),
        Entry("Budesonide", "Inhaled corticosteroid for asthma; oral form for Crohn's and colitis", MedRoute.INHALED),
        Entry("Bumetanide", "Loop diuretic (water pill) for fluid overload"),
        Entry("Buprenorphine", "Opioid used for chronic pain and opioid dependence"),
        Entry("Bupropion (Wellbutrin)", "Antidepressant that also helps with quitting smoking"),
        Entry("Buspirone", "Non-sedating medicine for ongoing anxiety"),
        Entry("Butalbital/acetaminophen/caffeine (Fioricet)", "Combination for tension headaches"),
        Entry("Calcium carbonate (Tums)", "Antacid and calcium supplement"),
        Entry("Candesartan", "ARB for high blood pressure and heart failure"),
        Entry("Carbamazepine", "Anticonvulsant for epilepsy and nerve pain"),
        Entry("Carbidopa/levodopa (Sinemet)", "Replaces dopamine to control Parkinson's symptoms"),
        Entry("Carvedilol", "Beta blocker for heart failure and high blood pressure"),
        Entry("Cefdinir", "Cephalosporin antibiotic for respiratory and skin infections"),
        Entry("Cefuroxime", "Cephalosporin antibiotic"),
        Entry("Cephalexin (Keflex)", "Cephalosporin antibiotic for skin and urinary infections"),
        Entry("Celecoxib (Celebrex)", "COX-2 anti-inflammatory for arthritis pain"),
        Entry("Cetirizine (Zyrtec)", "Low-drowsiness antihistamine for allergies"),
        Entry("Chlorthalidone", "Thiazide-type water pill for high blood pressure"),
        Entry("Cholecalciferol (vitamin D3)", "Supplement for bone health and low vitamin D"),
        Entry("Ciprofloxacin", "Fluoroquinolone antibiotic"),
        Entry("Citalopram (Celexa)", "SSRI antidepressant"),
        Entry("Clarithromycin", "Macrolide antibiotic"),
        Entry("Clindamycin", "Antibiotic for dental, skin and anaerobic infections"),
        Entry("Clonazepam (Klonopin)", "Benzodiazepine for seizures and panic disorder"),
        Entry("Clonidine", "Lowers blood pressure; also used for ADHD and withdrawal symptoms"),
        Entry("Clopidogrel (Plavix)", "Antiplatelet that helps prevent heart attack and stroke"),
        Entry("Clotrimazole", "Antifungal cream for yeast infections and ringworm", MedRoute.TOPICAL),
        Entry("Codeine", "Opioid for mild-to-moderate pain and cough"),
        Entry("Colchicine", "Relieves and prevents gout attacks"),
        Entry("Cyclobenzaprine", "Muscle relaxant for short-term back and neck spasm"),
        Entry("Cyclosporine", "Immunosuppressant for transplants and severe autoimmune disease"),
        Entry("Dabigatran (Pradaxa)", "Blood thinner that prevents clots and stroke"),
        Entry("Dapagliflozin (Farxiga)", "SGLT2 inhibitor for diabetes, heart failure and kidney disease"),
        Entry("Dexamethasone", "Potent corticosteroid for inflammation and swelling"),
        Entry("Dextromethorphan", "Cough suppressant found in many cold remedies"),
        Entry("Diazepam (Valium)", "Benzodiazepine for anxiety, muscle spasm and seizures"),
        Entry("Diclofenac", "NSAID for arthritis and pain, as a tablet or gel"),
        Entry("Dicyclomine", "Antispasmodic that eases cramping in irritable bowel syndrome"),
        Entry("Digoxin", "Strengthens the heartbeat and helps control its rhythm"),
        Entry("Diltiazem", "Calcium channel blocker for blood pressure and heart rhythm"),
        Entry("Diphenhydramine (Benadryl)", "Sedating antihistamine for allergies and occasional sleep"),
        Entry("Divalproex/valproate", "Anticonvulsant and mood stabiliser"),
        Entry("Docusate", "Stool softener for constipation"),
        Entry("Donepezil (Aricept)", "Boosts memory chemicals in Alzheimer's disease"),
        Entry("Dorzolamide", "Eye drops that lower pressure in glaucoma", MedRoute.OPHTHALMIC),
        Entry("Doxazosin", "Alpha blocker for blood pressure and an enlarged prostate"),
        Entry("Doxycycline", "Tetracycline antibiotic; also used for acne and malaria prevention"),
        Entry("Dulaglutide (Trulicity)", "Weekly GLP-1 injection for type 2 diabetes", MedRoute.INJECTABLE),
        Entry("Duloxetine (Cymbalta)", "SNRI for depression, anxiety and nerve pain"),
        Entry("Empagliflozin (Jardiance)", "SGLT2 inhibitor for diabetes and heart failure"),
        Entry("Enalapril", "ACE inhibitor for high blood pressure and heart failure"),
        Entry("Enoxaparin (Lovenox)", "Injectable blood thinner", MedRoute.INJECTABLE),
        Entry("Ergocalciferol (vitamin D2)", "Vitamin D supplement"),
        Entry("Escitalopram (Lexapro)", "SSRI for depression and anxiety"),
        Entry("Esomeprazole (Nexium)", "Proton pump inhibitor for reflux and ulcers"),
        Entry("Estradiol", "Oestrogen for menopause symptoms and hormone therapy"),
        Entry("Eszopiclone (Lunesta)", "Sleep aid for insomnia"),
        Entry("Ethinyl estradiol/norgestimate", "Combined oral contraceptive pill"),
        Entry("Ezetimibe", "Lowers cholesterol by blocking its absorption in the gut"),
        Entry("Famotidine (Pepcid)", "H2 blocker that reduces stomach acid"),
        Entry("Febuxostat", "Lowers uric acid to prevent gout"),
        Entry("Felodipine", "Calcium channel blocker for high blood pressure"),
        Entry("Fenofibrate", "Lowers triglycerides"),
        Entry("Ferrous sulfate", "Iron supplement for iron-deficiency anaemia"),
        Entry("Fexofenadine (Allegra)", "Non-drowsy antihistamine for allergies"),
        Entry("Finasteride", "Shrinks the prostate; also treats male hair loss"),
        Entry("Fish oil (omega-3)", "Supplement that can lower triglycerides"),
        Entry("Fluconazole (Diflucan)", "Antifungal for yeast infections"),
        Entry("Fluoxetine (Prozac)", "SSRI antidepressant"),
        Entry("Fluticasone", "Inhaled or nasal corticosteroid for asthma and allergies", MedRoute.INHALED),
        Entry("Folic acid", "B-vitamin supplement, important before and during pregnancy"),
        Entry("Furosemide (Lasix)", "Loop diuretic (water pill) for fluid overload"),
        Entry("Gabapentin (Neurontin)", "Calms nerve pain and helps control seizures"),
        Entry("Gemfibrozil", "Lowers triglycerides"),
        Entry("Glimepiride", "Sulfonylurea that lowers blood sugar in type 2 diabetes"),
        Entry("Glipizide", "Sulfonylurea for type 2 diabetes"),
        Entry("Glyburide", "Sulfonylurea for type 2 diabetes"),
        Entry("Guaifenesin (Mucinex)", "Expectorant that loosens chest congestion"),
        Entry("Haloperidol", "Antipsychotic for schizophrenia and severe agitation"),
        Entry("Hydralazine", "Widens blood vessels to lower blood pressure"),
        Entry("Hydrochlorothiazide (HCTZ)", "Thiazide water pill for high blood pressure"),
        Entry("Hydrocortisone", "Mild corticosteroid cream for skin irritation", MedRoute.TOPICAL),
        Entry("Hydroxychloroquine (Plaquenil)", "For lupus and rheumatoid arthritis"),
        Entry("Hydroxyzine", "Antihistamine for itching and anxiety"),
        Entry("Hyoscyamine", "Antispasmodic for stomach and bladder cramps"),
        Entry("Ibuprofen (Advil, Motrin)", "NSAID for pain, fever and inflammation"),
        Entry("Indomethacin", "Strong NSAID for gout and arthritis"),
        Entry("Insulin aspart (NovoLog)", "Rapid-acting insulin taken with meals", MedRoute.INJECTABLE),
        Entry("Insulin glargine (Lantus)", "Long-acting background insulin", MedRoute.INJECTABLE),
        Entry("Ipratropium (Atrovent)", "Inhaled bronchodilator for COPD", MedRoute.INHALED),
        Entry("Irbesartan", "ARB for high blood pressure and diabetic kidney disease"),
        Entry("Isosorbide mononitrate", "Nitrate that helps prevent angina chest pain"),
        Entry("Ketoconazole", "Antifungal, as a shampoo, cream or tablet", MedRoute.TOPICAL),
        Entry("Ketorolac", "Strong NSAID for short-term pain relief"),
        Entry("Labetalol", "Beta blocker for high blood pressure, often used in pregnancy"),
        Entry("Lamotrigine (Lamictal)", "Anticonvulsant and bipolar mood stabiliser"),
        Entry("Lansoprazole (Prevacid)", "Proton pump inhibitor for reflux and ulcers"),
        Entry("Latanoprost", "Eye drops that lower pressure in glaucoma", MedRoute.OPHTHALMIC),
        Entry("Leflunomide", "Disease-modifying medicine for rheumatoid arthritis"),
        Entry("Letrozole", "Aromatase inhibitor for breast cancer; also used in fertility care"),
        Entry("Levetiracetam (Keppra)", "Anticonvulsant for epilepsy"),
        Entry("Levocetirizine (Xyzal)", "Low-drowsiness antihistamine for allergies"),
        Entry("Levofloxacin", "Fluoroquinolone antibiotic"),
        Entry("Levonorgestrel", "Progestin used for regular and emergency contraception"),
        Entry("Levothyroxine (Synthroid)", "Thyroid hormone for an underactive thyroid"),
        Entry("Linagliptin", "DPP-4 inhibitor for type 2 diabetes"),
        Entry("Liraglutide (Victoza)", "Daily GLP-1 injection for diabetes and weight management", MedRoute.INJECTABLE),
        Entry("Lisdexamfetamine (Vyvanse)", "Stimulant for ADHD"),
        Entry("Lisinopril", "ACE inhibitor for high blood pressure and heart failure"),
        Entry("Lithium", "Mood stabiliser for bipolar disorder"),
        Entry("Loperamide (Imodium)", "Slows the gut to control diarrhoea"),
        Entry("Loratadine (Claritin)", "Non-drowsy antihistamine for allergies"),
        Entry("Lorazepam (Ativan)", "Benzodiazepine for anxiety and seizures"),
        Entry("Losartan (Cozaar)", "ARB for high blood pressure and kidney protection"),
        Entry("Lovastatin", "Statin that lowers cholesterol"),
        Entry("Magnesium oxide", "Supplement and mild laxative"),
        Entry("Medroxyprogesterone", "Progestin for contraception and hormone therapy"),
        Entry("Melatonin", "Sleep-cycle hormone used for insomnia and jet lag"),
        Entry("Meloxicam", "Once-daily NSAID for arthritis"),
        Entry("Memantine (Namenda)", "For moderate-to-severe Alzheimer's disease"),
        Entry("Mesalamine", "Anti-inflammatory for ulcerative colitis"),
        Entry("Metformin", "First-choice tablet for type 2 diabetes; lowers blood sugar"),
        Entry("Methadone", "Long-acting opioid for pain and addiction treatment"),
        Entry("Methocarbamol", "Muscle relaxant for musculoskeletal pain"),
        Entry("Methotrexate", "For rheumatoid arthritis, psoriasis and some cancers"),
        Entry("Methylphenidate (Ritalin, Concerta)", "Stimulant for ADHD"),
        Entry("Methylprednisolone", "Corticosteroid for inflammation and flare-ups"),
        Entry("Metoclopramide", "Relieves nausea and speeds stomach emptying"),
        Entry("Metoprolol", "Beta blocker for blood pressure, angina and heart failure"),
        Entry("Metronidazole (Flagyl)", "Antibiotic for anaerobic and parasitic infections"),
        Entry("Miconazole", "Antifungal cream for yeast infections and ringworm", MedRoute.TOPICAL),
        Entry("Mirtazapine", "Antidepressant that also improves sleep and appetite"),
        Entry("Modafinil", "Promotes wakefulness in narcolepsy and shift-work sleep disorder"),
        Entry("Montelukast (Singulair)", "Prevents asthma and allergy symptoms"),
        Entry("Morphine", "Strong opioid for severe pain"),
        Entry("Mupirocin", "Antibiotic ointment for minor skin infections", MedRoute.TOPICAL),
        Entry("Nadolol", "Long-acting beta blocker"),
        Entry("Naloxone (Narcan)", "Reverses an opioid overdose", MedRoute.NASAL),
        Entry("Naltrexone", "Blocks the reward from opioids and alcohol in addiction treatment"),
        Entry("Naproxen (Aleve)", "NSAID for pain and inflammation"),
        Entry("Nebivolol", "Beta blocker for high blood pressure"),
        Entry("Nifedipine", "Calcium channel blocker for blood pressure and angina"),
        Entry("Nitrofurantoin (Macrobid)", "Antibiotic for urinary tract infections"),
        Entry("Nitroglycerin", "Fast relief of angina chest pain", MedRoute.SUBLINGUAL),
        Entry("Nortriptyline", "Tricyclic antidepressant, also used for nerve pain"),
        Entry("Nystatin", "Antifungal for oral and skin yeast infections", MedRoute.TOPICAL),
        Entry("Olanzapine (Zyprexa)", "Antipsychotic for schizophrenia and bipolar disorder"),
        Entry("Olmesartan", "ARB for high blood pressure"),
        Entry("Omeprazole (Prilosec)", "Proton pump inhibitor for reflux and ulcers"),
        Entry("Ondansetron (Zofran)", "Prevents nausea and vomiting"),
        Entry("Orlistat", "Blocks some dietary fat absorption for weight loss"),
        Entry("Oseltamivir (Tamiflu)", "Antiviral that shortens influenza"),
        Entry("Oxcarbazepine", "Anticonvulsant for epilepsy"),
        Entry("Oxybutynin", "Calms an overactive bladder"),
        Entry("Oxycodone", "Opioid for moderate-to-severe pain"),
        Entry("Pantoprazole (Protonix)", "Proton pump inhibitor for reflux and ulcers"),
        Entry("Paroxetine (Paxil)", "SSRI for depression and anxiety"),
        Entry("Penicillin V", "Narrow-spectrum antibiotic for strep throat and other infections"),
        Entry("Phentermine", "Short-term appetite suppressant for weight loss"),
        Entry("Phenobarbital", "Long-acting anticonvulsant and sedative"),
        Entry("Phenytoin (Dilantin)", "Anticonvulsant for epilepsy"),
        Entry("Pioglitazone", "Improves the body's response to insulin in type 2 diabetes"),
        Entry("Polyethylene glycol (MiraLAX)", "Osmotic laxative for constipation"),
        Entry("Potassium chloride", "Replaces low potassium"),
        Entry("Pravastatin", "Statin that lowers cholesterol"),
        Entry("Prazosin", "Alpha blocker for blood pressure; also used for PTSD nightmares"),
        Entry("Prednisolone", "Corticosteroid for inflammation and allergic reactions"),
        Entry("Prednisone", "Oral corticosteroid for inflammation, asthma and autoimmune flares"),
        Entry("Pregabalin (Lyrica)", "For nerve pain, fibromyalgia and seizures"),
        Entry("Progesterone", "Hormone for menopause therapy and pregnancy support"),
        Entry("Promethazine", "Antihistamine for nausea, allergy and sedation"),
        Entry("Propranolol", "Beta blocker for blood pressure, tremor and migraine prevention"),
        Entry("Pseudoephedrine (Sudafed)", "Decongestant for a blocked nose"),
        Entry("Psyllium (Metamucil)", "Fibre supplement for regularity and cholesterol"),
        Entry("Quetiapine (Seroquel)", "Antipsychotic for schizophrenia, bipolar disorder and depression add-on"),
        Entry("Quinapril", "ACE inhibitor for high blood pressure"),
        Entry("Rabeprazole", "Proton pump inhibitor for reflux and ulcers"),
        Entry("Raloxifene", "Prevents osteoporosis after menopause"),
        Entry("Ramipril", "ACE inhibitor for blood pressure and heart protection"),
        Entry("Risedronate", "Bisphosphonate for osteoporosis"),
        Entry("Risperidone (Risperdal)", "Antipsychotic for schizophrenia and bipolar disorder"),
        Entry("Rivaroxaban (Xarelto)", "Blood thinner that prevents clots and stroke"),
        Entry("Rizatriptan (Maxalt)", "Stops migraine attacks"),
        Entry("Ropinirole", "For Parkinson's disease and restless legs syndrome"),
        Entry("Rosuvastatin (Crestor)", "Statin that lowers cholesterol"),
        Entry("Sacubitril/valsartan (Entresto)", "For chronic heart failure"),
        Entry("Semaglutide (Ozempic, Wegovy)", "GLP-1 injection for type 2 diabetes and weight management", MedRoute.INJECTABLE),
        Entry("Sertraline (Zoloft)", "SSRI for depression, anxiety and OCD"),
        Entry("Sildenafil (Viagra)", "For erectile dysfunction; also pulmonary hypertension"),
        Entry("Simvastatin (Zocor)", "Statin that lowers cholesterol"),
        Entry("Sitagliptin (Januvia)", "DPP-4 inhibitor for type 2 diabetes"),
        Entry("Sotalol", "Beta blocker that also treats abnormal heart rhythms"),
        Entry("Spironolactone", "Potassium-sparing water pill for heart failure, blood pressure and acne"),
        Entry("Sucralfate", "Coats and protects stomach and intestinal ulcers"),
        Entry("Sulfasalazine", "For rheumatoid arthritis and ulcerative colitis"),
        Entry("Sumatriptan (Imitrex)", "Stops migraine attacks"),
        Entry("Tacrolimus", "Immunosuppressant for transplants; ointment for eczema"),
        Entry("Tadalafil (Cialis)", "For erectile dysfunction and an enlarged prostate"),
        Entry("Tamoxifen", "Blocks oestrogen in breast cancer treatment and prevention"),
        Entry("Tamsulosin (Flomax)", "Eases urination with an enlarged prostate"),
        Entry("Telmisartan", "ARB for high blood pressure"),
        Entry("Terazosin", "Alpha blocker for blood pressure and prostate symptoms"),
        Entry("Terbinafine", "Antifungal for nail and skin infections"),
        Entry("Testosterone", "Hormone replacement for low testosterone", MedRoute.TRANSDERMAL),
        Entry("Timolol", "Beta blocker eye drops for glaucoma", MedRoute.OPHTHALMIC),
        Entry("Tiotropium (Spiriva)", "Once-daily inhaler for COPD", MedRoute.INHALED),
        Entry("Tizanidine", "Muscle relaxant for spasticity"),
        Entry("Topiramate (Topamax)", "For seizures and migraine prevention"),
        Entry("Torsemide", "Loop diuretic (water pill) for fluid overload"),
        Entry("Tramadol", "Opioid-like pain reliever for moderate pain"),
        Entry("Trazodone", "Antidepressant, often used in low doses for sleep"),
        Entry("Triamcinolone", "Corticosteroid cream or nasal spray", MedRoute.TOPICAL),
        Entry("Triamterene/hydrochlorothiazide", "Combination water pill for high blood pressure"),
        Entry("Trimethoprim/sulfamethoxazole (Bactrim)", "Antibiotic for UTIs, skin and other infections"),
        Entry("Valacyclovir (Valtrex)", "Antiviral for cold sores, shingles and genital herpes"),
        Entry("Valsartan (Diovan)", "ARB for high blood pressure and heart failure"),
        Entry("Vardenafil (Levitra)", "For erectile dysfunction"),
        Entry("Varenicline (Chantix)", "Helps with quitting smoking"),
        Entry("Venlafaxine (Effexor)", "SNRI for depression and anxiety"),
        Entry("Verapamil", "Calcium channel blocker for blood pressure, rhythm and cluster headache"),
        Entry("Vitamin B12 (cyanocobalamin)", "Supplement for vitamin B12 deficiency"),
        Entry("Warfarin (Coumadin)", "Blood thinner that needs regular INR blood tests"),
        Entry("Zolpidem (Ambien)", "Short-term sleep aid for insomnia"),
        Entry("Zonisamide", "Anticonvulsant for epilepsy"),
    ).sortedBy { it.name.lowercase() }

    /** The section letters present in [ALL], in display order. */
    val SECTIONS: List<String> = ALL.map { it.section }.distinct()

    fun search(query: String): List<Entry> =
        if (query.isBlank()) ALL else ALL.filter { it.matches(query) }
}
